#!/usr/bin/env bash

set -e
name=`git config --global user.name` 
email=`git config --global user.email` 
contributar_info="$name ($email)"
copyright_tmpl="/* (C) Copyright 2007 Free Software Foundation GPL3.
 *   The GNU General Public License is a free, copyleft license for
 * software and other kinds of works.
 * 
 *   The licenses for most software and other practical works are designed
 * to take away your freedom to share and change the works.  By contrast,
 * the GNU General Public License is intended to guarantee your freedom to
 * share and change all versions of a program--to make sure it remains free
 * software for all its users.  We, the Free Software Foundation, use the
 * GNU General Public License for most of our software; it applies also to
 * any other work released this way by its authors.  You can apply it to
 * your programs, too.
 *
 * Contributors:
 *     ${contributar_info}. */
"

header_tmpl='
#ifndef ICARYX__%s
#define ICARYX__%s

#include "namespace.h"

NAMESPACE__ICARYX_START

NAMESPACE__ICARYX_END

#endif // ICARYX__%s
'

src_tmpl='
#include "namespace.h"

NAMESPACE__ICARYX_START

NAMESPACE__ICARYX_END
'

editor_tmpl='
/*
  Local Variables:
  mode: c++
  End:
*/
'

usage() {
    echo "Usage: $0 <filename>"
    exit 1
}

if [ $# -ne 1 ]; then
    usage
fi

filename="$1"
ext="${filename##*.}"

# Generate a UUID and replace '-' with '_'
uuid=$(uuidgen | tr '-' '_')

header_file() {
    {
        echo "$copyright_tmpl"
        printf "$header_tmpl" "$uuid" "$uuid" "$uuid"
        echo "$editor_tmpl"
    } > "$filename"
}

src_file() {
    {
        echo "$copyright_tmpl"
        echo "$src_tmpl"
        echo "$editor_tmpl"
    } > "$filename"
}

case "$ext" in
    h|hpp)
        header_file
        ;;
    *)
        src_file
        ;;
esac

echo "File '$filename' generated successfully."
